### ISSUE TITLE
Support's For Other Sites.

### ISSUE THREAD

**Issue by Deadlyhacker** [Seuntjie900/DiceBot#17]
Are you planning to add more sites to your bot @Seuntjie900 

I Want you to add support for this sites.

1)www.bitsler.com
2)freebitcoingame.com
3)freebitco.in

Thanks.

**Comment by Seuntjie900** [comment]
Kindly see the FAQ on my website, specifically the "Can you add my site to the bot?" question: https://bot.seuntjie.com/FAQs.aspx#faq8

If the sites have a public API, it'll probably be 0.5Btc per site. If they don't have APIs, it'll likely be closer to 0.8-1.0 Btc per site, depending on the site itself. Usually I suggest that you correspond with the site owners/operators as well as other users and try to convince them to make the investment.

**Comment by Deadlyhacker** [comment]
I Dont have enough BTC for this :(
Sites in upper post is not belongs to me by the way as well it was something make bot better for users
They Will not listen me about make investment maybe you can connact them since you are earning the BTC ?

Thanks.

**Comment by Seuntjie900** [comment]
I know they don't belong to you, that's why I suggested you contact the owners of the site and try to convince them.

If I as a developer contact them, it just sounds like a sales pitch and they're les likely to want to make the investment. If YOU as a PLAYER contact them, it will show the owners/operators that it's something that their CLIENTS want and is therefore more likely to go for it. Talk to your fellow players, get them to agree with you that they'll want to use the bot on the sites and then contact the admins about it.

**Comment by Deadlyhacker** [comment]
Okay I Have Tried and you cant event type "bot","automation" to their support to their chat so no way ı think :/

This can be closed ı cant do this myself sorry.
