### ISSUE TITLE
Reseting Stats

### ISSUE THREAD

**Issue by Bullnados** [Seuntjie900/DiceBot#2]
doesn't reset "Maximum bets"

**Comment by Seuntjie900** [comment]
The maximum bets value is calculated based on your balance and betting strategy. It's not supposed reset.

**Comment by Bullnados** [comment]
Ok. But one question I switched PC same settings same balance but different maximum bets?

**Comment by Seuntjie900** [comment]
The max bet takes only certain martingale settings into account. It's an outdated stat that i have considered removing, since it is nearly impossible to accurately predict the max number of bets for some strategies.

In otherwords, even if your fibonacci settings on both computers are the same, if the right martingale settings differ slightly, the max bet value will differ as well.
