### ISSUE TITLE
Control Bot Speed via Programmer Mode

### ISSUE THREAD

**Issue by KryptoNova** [Seuntjie900/DiceBot#38]
Hello,

I would like to be able to control the bot speed using lua commands.  I reviewed the code to determine how the "BotSpeedEnabled" and "BotSpeedValue" keys are stored in the PSavesNames dictonary.

Depending on the site and the bet as it increases through a martingale, it would be nice to be able to make the bot move faster or slower.  Right now, due to the betting strategy and lack of bankroll, I am getting lots of exceeding bet rate messages until I advance to the higher betting portions of my strategy.

Would it be possible to have an enhancement to move these two keys from the PSavesNames into the SaveNames dictionary so that they can be utilized through the Programmer Mode's getvalue, setvalueboolean, and setvaluedecimal functions?

I would do it myself and create a push, but I cannot seem to get the environment right to compile and I'm not exactly sure why some things are in PSavesNames vs. SavesNames.

I appreciate any considerations or recommendations you may have related to this enhancement.  Thank you!

**Comment by Seuntjie900** [comment]
PSaveNames are personal settings, things like betting speeds, withdrawal address, live bets count, sound notification settings etc. SaveNames are strategy settings, thing that directly influence the bet properties (chance, amount, high/low etc.)

I'm hesitant to allow changing these settings setting from the programmer mode, since the settings are stored when the bot is closed. This is also why I don't allow you to change the withdrawal address or similar settings from the programmer mode.

**Comment by Seuntjie900** [comment]
If you absolutely need to slow the bot down based on the size of your bets you can use the sleep function in lua. It will result in the bot UI freezing the whole time while the LUA environment sleeps, but the bets will be delayed by whatever time you set

**Comment by KryptoNova** [comment]
Thank you for the reply.  I figured that there was a reason why those were off limits to programmer mode.  

I will just let the bot go into its stand by mode while it waits for a second.  I haven't run into any problems yet with being blocked or anything.  I'm thinking that there is some sort of algorithm that will balance out the requests by adjusting the poling time accordingly.  I may just not have let the bot run long enough to calibrate.
