### ISSUE TITLE
Verify seed on every roll.

### ISSUE THREAD

**Issue by daegontaven** [Seuntjie900/DiceBot#45]
Most dice sites nowadays have a server seed + client seed mechanism. But this is in fact misleading because of the way you have to ask for the seed beforehand every time you bet to make sure they are not cheating when we look away. 

Can anyone implement a verifyseed() function that can be called in the programmer mode.

**Comment by Seuntjie900** [comment]
daegontaven different sites use different RNGs. Some change the seeds with every bet, other just increment a number (called the nonce) with every bet, but the server and client seeds stay the same. 

For nonce based RNG, the bot saves the client seed and server seed hash as best it can for each bet, but if there are bets where they're not stored or stored incorrectly, you can deduce the values from the other bets of the same seeds (since they will be the same).

As for sites using per bet based seeds, the bot stores the server seed hash in memory and writes it to the db when a bet result is received, along with the server seed and the random client seed that the bot picked. With all of the per bet based sites, the server seed hash for the next bet is provided both on login (if not, the bot gets the hash from the API before completing the login procedure) and with the result of each bet. There's no need to force the bot to go get the server seed hash after each bet.

I'm not sure whether you want verifyseed() to ensure that the bot has the seeds, which it does automatically and there's no need for you to check it, or if you want the bot to verify the last roll, which is not practical for a lot of sites.

**Comment by daegontaven** [comment]
@Seuntjie900 Thank you for replying. Yes I am talking about per bet based sites. I know you've read this https://bitcointalk.org/index.php?topic=948965 and unfortunately many sites are also using this same trick to hide their schemes. Also It is a handy function to have. I would write change myself but I don't know cs.

**Comment by Seuntjie900** [comment]
That topic is 2 years old and outdated. From 999dices web API documentation (https://www.999dice.com/api/):

```
 **_PlaceBet_**
Place a bet
_Request:_
a: PlaceBet
s: User's session cookie
PayIn: The bet amount, in satoshis
Low: The low number in the user's guess range. The guess range must be between 0-999,999.
High: The high number in the user's guess range. The guess range must be between 0-999,999.
ClientSeed: The seed to use for this bet (32 bit signed integer)
Currency: btc/doge/ltc/eth
ProtocolVersion: 2 [All bot owners should update their code to set this value to opt in to the new response format]
_Response:_
BetId: The bet's ID.
PayOut: The payout from the bet (subtract PayIn to calculate profit)
Secret: The secret number from the bet.
StartingBalance: Your balance just before placing the bet, in satoshis.
ServerSeed: The server seed used to generate the bet.
**Next: The next server seed hash (If all 0's, check the Warning field)**
_Errors:_
ChanceTooHigh: 1 (The chance to win is too high. It must be between 5% and 95%)
ChanceTooLow: 1 (The chance to win is too low. It must be between 5% and 95%)
InsufficientFunds: 1 (The user has insufficient funds to make this bet)
NoPossibleProfit: 1 (There is no possible way for the user to profit from this bet)
MaxPayoutExceeded: 1 (The bet, if won, would exceed the maximum possible payout for the casino)
```

The hash for the next bet is returned with the result of your current bet. This is true for all sites in the bot that uses a per bet based RNG. When negotiating the sites, that is something I required from the site, and warn that if they do not provide it, I will query the site for the next seed between each bet, which will result in slow bets and higher server load.

No changes need to be made. The bot already does automatically, with the help of the sites, what you want to do manually.
