### ISSUE TITLE
Doesn't Stop After Error.

### ISSUE THREAD

**Issue by gdoctors** [Seuntjie900/DiceBot#56]
If bot get bet higher than balance it throws an error and waits (instead of stopping like it should). then you redeposit more money and the bot continues where it left off. 

it should either be set as an option to continue or even have a pop up asking do you want to continue or reset.

**Comment by Seuntjie900** [comment]
The current behavior is intended. It was often requested that the bot automatically retry a bet if there is an error or if the fund run out, because many people ran the bot on a server and wanted the bot to resume where it left off after a deposit, or just keep on going if a network error occurred.

Also, the bot does not differentiate between bet errors at the time (because of the wide range of possible errors). It views a network error, invalid bet, balance too low etc all as just an error. Often, it is also not possible to define or catch the type of error, as the sites do not all return details about the error.

While I do agree there should be a setting to define the behavior, it is outside of the scope of maintenance being performed on version 3 of the bot at this time. A popup would break the intended functionality of resuming automatically without user interaction though.

**Comment by gdoctors** [comment]
I highly believe that this should be an option. If this feature was added into the bot as a feature it could be made as an option to turn this feature on or off. 

It is very deceptive to me because in my eyes when a bot throws an error and it should stop. Then when I deposit more money, it should wait for me to tell it to continue if i so choose. I ended up losing a large amount of money because I didn't know that the bot will continue after an error. 

I ended up losing a total of 0.09 BTC because of this "feature." I also know of other people who have lost balances as high as 0.6 BTC because of this also. 

I am not asking for my money back from you but at least help me to remedy this situation so that more loss is prevented. Unless there is a kickback from the dice sites, there is no reason why this cannot be resolved. If that is the case then that would be a different issue all together.
