### ISSUE TITLE
Fibbonaci: When level xx is reached

### ISSUE THREAD

**Issue by Bullnados** [Seuntjie900/DiceBot#9]
I noticed that the lose counter is reseted after u won one time. But it would be better to reset the counter after lvl 0 or lvl1 is reached.
Problem f.e. Stop at lvl 8:

--start--
lose
lose
lose
lose
lose
lose
win
lose
lose
lose
lose
--end--

Here u can see the problem. The counter "think" bot is at lvl 6, because after the 6th lose there is a win. But after that win u are firstly at lvl 4. For the bot the 5th loose is again just lvl 1. But in reality it is already lvl 5.

Hope u can understand my exception.

**Comment by Seuntjie900** [comment]
The bot handles the levels exactly as intended. YOU have to tell the bot whether to reset on a win, to increment or to stop playing. If you set the bot to reset on a win, it changes the level to 1, if you set it to increment with -2, it adds -2 to the current level (6+(-2)=4).

I don't understand what your problem is or what you think is happening here.

You can see the code handling the fibonacci levels here: https://github.com/Seuntjie900/DiceBot/blob/master/DiceBot/cDiceBot.cs#L1603

**Comment by Bullnados** [comment]
You are completly right. Sorry for that "issue". But i can swear i have such an issue. mmh
